// Uitvoeringsdeck van de workshop "Agentic data science in het onderwijs" (120 min).
// Dit is wat op de dag op het scherm staat; het voorstel is 261005_workshop_rad_voorstel.deck.mjs.
// Draaiboek: workshop-rad/docs/programma-uitvoering.md. Casus: A (eerstejaarsuitval).
// Bouwen vanuit de projectroot:
//   node ~/.claude/skills/powerclaude/scripts/build.mjs workshop-rad/decks/261005_workshop_rad_uitvoering.deck.mjs
export default {
  title: 'Agentic data science in het onderwijs: jij stuurt, de agent bouwt',
  author: 'CEDA',
  slides: [
    // 1-4 Intro (0:00, 5 min)
    {
      type: 'title',
      kicker: 'CEDA · DAIR-bijeenkomst',
      title: 'Jij stuurt, de agent bouwt',
      lede: 'Agentic data science in het onderwijs',
      sub: '120 minuten · één casus · één dashboard',
      agenda: ['Data verkennen', 'Dashboard bouwen', 'Evaluatie en vervolg'],
      tagline: 'Moving Education.',
      notes: 'Welkom. Zeg in een zin wat vandaag gebeurt: in tweetallen werken met een AI-agent aan één casus, en een dashboard opleveren dat de vraag beantwoordt. Schrijf de eindtijd op een bord: 15:00 bijvoorbeeld.',
    },
    { type: 'ceda' },
    {
      type: 'table',
      variant: 'licht-blauw',
      title: 'Zo loopt de middag',
      columns: ['Tijd', 'Blok', 'Duur'],
      widths: [0.15, 0.7, 0.15],
      rows: [
        ['0:00', 'Intro, synthetische data, casus', '17 min'],
        ['0:17', 'Skills, prompts en de devcontainer', '13 min'],
        ['0:30', 'Ronde 1: data verkennen', '22 min'],
        ['0:52', 'Spiegelmoment 1', '15 min'],
        ['1:07', 'Ronde 2: dashboard bouwen', '22 min'],
        ['1:29', 'Spiegelmoment 2', '15 min'],
        ['1:44', 'Evaluatie en vervolg', '8 min'],
        ['1:52', 'Afsluiting', '8 min'],
      ],
      notes: 'Loop het schema in dertig seconden door. Benadruk de spiegelmomenten: daar leer je het meest, omdat je ziet wat de groep naast je deed. Het evaluatieblok vóór de afsluiting is nieuw: we vragen straks wat jullie ervan vonden en of er een vervolg moet komen.',
    },
    {
      type: 'section',
      variant: 'blauw',
      title: 'Jij stuurt, de agent programmeert',
      text: 'Er is geen goed of fout dashboard, alleen keuzes die je kunt uitleggen.',
      illustration: 'kunstmatigeintelligentie',
      notes: 'Spelregels: iedereen werkt via de agent, niemand hoeft te kunnen programmeren, wel kritisch kijken. Doel aan het eind: een kwalitatief antwoord op de casusvraag, onderbouwd met je dashboard.',
    },
    // 5 Synthetische data (0:05, 6 min)
    {
      type: 'split',
      variant: 'licht-roze',
      title: 'De data is synthetisch, het patroon is ingebouwd',
      bullets: [
        '**Fictief:** zelfde kolommen en codes als 1CHO, maar geen echte personen',
        '**Mag de agent in:** geen AVG-toets of verwerkersovereenkomst nodig',
        '**Bewust gemaakt:** er zit een echt verschil én een nep-verschil in',
        '**Alleen oefenen:** de kansen zijn onze keuze, geen werkelijkheid',
      ],
      illustration: 'Slot',
      notes: 'Wat is synthetisch: gegenereerd naar het patroon van een echt bestand. Zeg hardop: er zit één echt verschil in en één dat alleen toeval is, we vertellen niet welke. Dat is de oefening. Validatie tegen de werkelijkheid doen we niet; dat vraagt echte data buiten de devcontainer.',
    },
    // 6-7 Opdracht en casus (0:11, 6 min)
    {
      type: 'cards',
      variant: 'licht-geel',
      title: 'Onze casus: eerstejaarsuitval',
      items: [
        { badge: 'A', tag: 'De vraag', title: 'Wie stopt na jaar 1?', sections: [{ text: 'Welke eerstejaars stoppen binnen een jaar, en verschilt dat per sector en opleidingsvorm?' }] },
        { badge: '→', tag: 'De AI-taak', title: 'Uitval per cohort', sections: [{ text: 'Uitval binnen 1 jaar per cohort berekenen en vergelijken naar sector, geslacht en opleiding.' }] },
        { badge: '✓', tag: 'Het product', title: 'Eén dashboard', sections: [{ text: 'Een dashboard dat de vraag beantwoordt, met de conclusie als titel.' }] },
      ],
      footer: 'Data: 3070 fictieve studenten, cohorten 2012-2023, één bestand: data/synthetisch_1cho.csv.',
      notes: 'Casus A gekozen omdat de data daar het sterkst op aansluit. Let op: opleidingsvorm heeft maar één waarde (voltijd). Wie dat zelf ontdekt, ziet waarom verkennen loont. Noem het niet vooraf.',
    },
    {
      type: 'split',
      variant: 'licht-blauw',
      title: 'Werk in tweetallen, wissel per ronde',
      bullets: [
        '**Bestuurder:** typt de instructies aan de agent',
        '**Navigator:** leest de code en controleert de uitkomst',
        '**Wissel** na ronde 1, zodat beiden beide rollen doen',
        '**Vraag je iets?** Dan stel ik een wedervraag: wat zou de agent hier doen?',
      ],
      illustration: 'gesprek',
      notes: 'Verdeel de tweetallen nu. Iedereen heeft een laptop met de devcontainer; check dat per tweetal één laptop werkt. Wat ze aan het eind in handen hebben: een eigen aanpak, gespiegeld aan de tweetallen om hen heen.',
    },
    // 8 Skills en prompts (0:17, 8 min)
    {
      type: 'cards',
      variant: 'blauw',
      title: 'Prompt, skill, agent',
      arrows: true,
      items: [
        { tag: 'Losse vraag', title: 'Prompt', sections: [{ text: 'Je typt wat je wilt. Elke keer anders, de kennis zit in jouw hoofd.' }, { label: 'Levert', text: 'Eén antwoord', strong: true }] },
        { tag: 'Vastgelegd recept', title: 'Skill', sections: [{ text: 'Een map met een SKILL.md: instructies, voorbeelden, checks. Leesbaar en deelbaar.' }, { label: 'Levert', text: 'Herhaalbare werkwijze', strong: true }] },
        { tag: 'Voert uit', title: 'Agent', sections: [{ text: 'Claude Code leest de skill, draait de code en toetst aan de checks.' }, { label: 'Levert', text: 'Resultaat dat je kunt nalopen', strong: true }] },
      ],
      footer: 'Vuistregel: elke prompt die je drie keer typt, is een skill in wording.',
      notes: 'Laat een echte SKILL.md zien, maximaal een minuut. Een goede prompt helpt jou vandaag, een goede skill helpt je hele team elke keer weer. Na elk spiegelmoment doet een skill in één instructie wat jullie net met de hand deden. Geen black box: je kunt lezen wat de agent gaat doen.',
    },
    // 9 Devcontainer en voorbeeldprompt (0:25, 5 min)
    {
      type: 'list',
      variant: 'licht-groen',
      title: 'Zo start je met de agent',
      items: [
        { title: 'Open de devcontainer', text: 'Alles staat klaar: Python, DuckDB, Streamlit, de data en de skills', status: 'Stap 1', color: 'groen' },
        { title: 'Start Claude Code', text: 'Typ claude in de terminal', status: 'Stap 2', color: 'groen' },
        { title: 'Probeer een eerste instructie', text: 'Lees data/synthetisch_1cho.csv en vertel in gewone taal wat erin zit', status: 'Stap 3', color: 'blauw' },
        { title: 'Activeer skill 1', text: '/workshop-verkennen: dat doen we straks bij het spiegelmoment', status: 'Later', color: 'oranje' },
      ],
      footnote: 'Duurt het starten langer dan een minuut? Roep iemand, dan zoeken we het samen uit.',
      notes: 'Doe de eerste instructie live voor, op het scherm. Laat zien dat de agent de code zichtbaar maakt. Activeren van de skills duurt maximaal een minuut; lukt dat niet, dan is dat een signaal over de devcontainer en niet over de deelnemer.',
    },
    // 10-11 Ronde 1 (0:30, 22 min)
    {
      type: 'section',
      variant: 'groen',
      number: 1,
      title: 'Ronde 1: ken je data',
      text: '22 minuten. Verken data en codebook voor je iets bouwt.',
      illustration: 'data',
      notes: 'Start de timer van 22 minuten. Loop rond; beantwoord vragen met een wedervraag. Let op: wie het laatste cohort meetelt (vertekend percentage), zit in de valkuil. Dat bespreken we bij het spiegelmoment.',
    },
    {
      type: 'cards',
      variant: 'licht-geel',
      title: 'Ronde 1: wat je doet en oplevert',
      numbered: true,
      items: [
        { tag: 'Verken', title: 'Wat zit erin?', sections: [{ text: 'Rijen, studenten, jaren, ontbrekende waarden, de definitie van uitval en instroom.' }] },
        { tag: 'Controleer', title: 'Wat mag je laten zien?', sections: [{ text: 'Kleine groepen en cohorten die nog niet afgelopen zijn. Wat telt wel en niet mee?' }] },
        { tag: 'Schets', title: 'Twee of drie views', sections: [{ text: 'Een schets op papier of in tekst van wat je gaat bouwen, met een conclusie als titel.' }] },
      ],
      footer: '**Oplevering:** begrip van de data, een schets en een eerste privacy-check.',
      notes: 'Dit is de bestuurder-navigator-ronde. Aan het eind van ronde 1 moeten ze kunnen zeggen hoeveel studenten en cohorten er zijn, welke cohorten niet waarneembaar zijn en waar kleine groepen zitten.',
    },
    // 12-13 Spiegelmoment 1 (0:52, 15 min)
    {
      type: 'section',
      variant: 'oranje',
      number: 2,
      title: 'Spiegelmoment 1: wat deden jullie?',
      text: 'Twee of drie tweetallen delen hun aanpak. Daarna doet skill 1 de ronde.',
      illustration: 'gesprek',
      notes: 'Vraag per tweetal één minuut: wat deden jullie, wat vonden jullie lastig, wat vonden jullie nog niet. Niet oordelen. Daarna draai je /workshop-verkennen op dezelfde data, live.',
    },
    {
      type: 'split',
      variant: 'licht-blauw',
      title: 'Skill 1 doet ronde 1 in één instructie',
      bullets: [
        '**Profiel:** rijen, studenten, cohorten, ontbrekende waarden',
        '**Definities:** staat1cho-definities van uitval, instroom en rendement',
        '**Kleine groepen:** onder 30 studenten, met secundaire onderdrukking',
        '**Schets:** twee of drie views als tussenproduct (schets.md)',
      ],
      illustration: 'Lamp',
      notes: 'Vergelijk samen: wat zag de skill wat jullie misten, en wat deden jullie wat de skill niet deed? Leg het verschil neer als bevinding. De definities komen uit het package staat1cho (CEDA). De drempel van 30 en 5 is een keuze van het project en nog niet getoetst door een privacy officer.',
    },
    // 14-16 Ronde 2 (1:07, 22 min)
    {
      type: 'section',
      variant: 'blauw',
      number: 3,
      title: 'Ronde 2: bouw het dashboard',
      text: '22 minuten. Wissel van rol en maak de conclusie zichtbaar.',
      illustration: 'Laptopman',
      notes: 'Wissel nu van rol. Timer 22 minuten. Loop rond met de responsible-checks in je hoofd: drempel, waarneembaarheid, framing, toegankelijkheid.',
    },
    {
      type: 'cards',
      variant: 'licht-groen',
      title: 'Wat je dashboard minimaal heeft',
      numbered: true,
      items: [
        { tag: 'Grafiek', title: 'Conclusie als titel', sections: [{ text: '"Uitval is het hoogst in techniek" in plaats van "Uitval per sector".' }] },
        { tag: 'Vergelijking', title: 'Eén nul-as', sections: [{ text: 'Groepen of cohorten naast elkaar, vergelijkbaar en eerlijk.' }] },
        { tag: 'Filter', title: 'Sector of cohort', sections: [{ text: 'Ook na het filteren worden kleine groepen niet getoond.' }] },
        { tag: 'Uitleg', title: 'Zo lees je dit', sections: [{ text: 'Definities, bron en wat het dashboard niet kan zeggen.' }] },
      ],
      footer: 'Het dashboard is het middel, de casusvraag het doel.',
      notes: 'Dit zijn de vier minimumeisen. Meer hoeft niet; liever een werkend en uitlegbaar dashboard dan een volle tabbladenwand.',
    },
    {
      type: 'cards',
      variant: 'licht-roze',
      title: 'Responsible zit in het bouwen',
      items: [
        { tag: 'Privacy', title: 'Drempel', sections: [{ text: 'Geen groepen onder de 30 studenten, geen percentages onder 5.' }] },
        { tag: 'Eerlijk', title: 'Geen oorzaak', sections: [{ text: 'Een verschil is nog geen oorzaak, en groepen worden niet gestigmatiseerd.' }] },
        { tag: 'Toegankelijk', title: 'Leesbaar', sections: [{ text: 'Kleurcontrast, alt-tekst en kleuren die ook zonder rood-groen werken.' }] },
        { tag: 'Bron', title: 'Uitleg', sections: [{ text: 'Bron, definities en peildatum bij elke grafiek.' }] },
      ],
      footer: 'Geen aparte stap achteraf: de skill past deze checks toe tijdens het bouwen.',
      notes: 'De agent bouwt snel. Jij bepaalt wat je mag concluderen. Na ronde 2 zie je wat jullie zelf misten.',
    },
    // 17-19 Spiegelmoment 2 (1:29, 15 min)
    {
      type: 'section',
      variant: 'oranje',
      number: 4,
      title: 'Spiegelmoment 2: wat bouwden jullie?',
      text: 'Toon twee of drie dashboards. Wat deed je anders, wat miste de agent?',
      illustration: 'gesprek',
      notes: 'Vraag per groep één minuut. Zet daarna de volgende dia nog niet aan: eerst vragen welke verschillen groepen op hun dashboard hadden staan (sector? geslacht?).',
    },
    {
      type: 'chart',
      variant: 'licht-geel',
      title: 'Techniek valt het vaakst uit, geslacht laat geen verschil zien',
      chart: 'bar',
      labels: ['Techniek', 'Economie', 'Gezondheidszorg', 'Totaal'],
      series: [{ name: 'Uitval binnen 1 jaar', values: [21.9, 13.1, 10.2, 16.7] }],
      format: '0.0"%"',
      takeaway: 'Het verschil tussen sectoren hebben wij ingebouwd. Man (16,1%) en vrouw (17,3%) verschillen niet echt: dat is toeval.',
      source: 'synthetische data, cohorten 2012-2022 (2023 is nog niet waarneembaar)',
      notes: 'De onthulling. Wie "vrouwen vallen vaker uit" op een dashboard had, ziet hier ruis. Gebruik dit als leermoment zonder beschuldiging. Antwoordsleutel: workshop-rad/data/verwachte_uitkomsten.txt.',
    },
    {
      type: 'split',
      variant: 'licht-blauw',
      title: 'Skill 2 bouwt het dashboard met de checks erin',
      bullets: [
        '**Bouwt:** grafiek, vergelijking en filter uit schets.md',
        '**Past toe:** drempel, waarneembaarheid, eerlijke framing, toegankelijkheid',
        '**Legt uit:** bron, definities en wat het dashboard niet kan zeggen',
        '**Jij bepaalt:** wat je mag concluderen en hoe je het presenteert',
      ],
      illustration: 'Vaantje geel met vink',
      notes: 'Laat skill 2 live draaien, laat de uitkomst kort zien en vergelijk met de dashboards van de groepen. De analist voegt de wijsheid toe: wat mag je concluderen en hoe presenteer je het?',
    },
    // 20-22 Evaluatie en vervolg (1:44, 8 min)
    {
      type: 'cards',
      variant: 'groen',
      title: 'Evaluatie en vervolg: 8 minuten',
      items: [
        { badge: '1', tag: '3 min', title: 'Terugblik', sections: [{ text: 'Wat vond je ervan? Wat ging goed, wat zag je nu pas?' }] },
        { badge: '2', tag: '2 min', title: 'Meerkeuzevraag', sections: [{ text: 'Zou je een vervolg willen, en hoe groot?' }] },
        { badge: '3', tag: '3 min', title: 'Open vraag', sections: [{ text: 'Wat wil je precies leren in zo’n training?' }] },
      ],
      footer: 'Anoniem en vrijwillig. De antwoorden bepalen of en hoe CEDA een vervolg inricht.',
      notes: 'Vraag eerst toestemming: de antwoorden zijn anoniem en gebruiken we om te bepalen of er een vervolg komt. Terugblik via workshop-reflectie of de peiling (QR-code). Gebruik de formulering uit workshop-rad/skills/workshop-reflectie/references/vragenset.md en verander die niet.',
    },
    {
      type: 'list',
      variant: 'licht-blauw',
      title: 'Zou je een vervolg op deze workshop willen?',
      items: [
        { title: 'Nee, niet nodig', text: 'Deze workshop was genoeg', status: 'A', color: 'blauw' },
        { title: 'Een losse sessie van een paar uur', text: 'Een vervolgworkshop, bijvoorbeeld met eigen data', status: 'B', color: 'blauw' },
        { title: 'Een paar dagdelen over enkele weken', text: 'Verdieping verspreid over meerdere dagen', status: 'C', color: 'blauw' },
        { title: '4 uur per week, één semester', text: 'Een volledig trainingsprogramma', status: 'D', color: 'blauw' },
      ],
      footnote: 'Kies wat het best past. Scan de QR-code of steek je hand op.',
      notes: 'Laat de peiling lopen, twee minuten. Als de peiling-tool nog niet gekozen is, tel handopsteking en noteer de aantallen. Voeg de QR-code hier toe zodra de tool bekend is.',
    },
    {
      type: 'section',
      variant: 'geel',
      title: 'Wat wil je precies leren?',
      text: 'Kort en concreet. Bijvoorbeeld: een eigen skill schrijven voor onze data.',
      illustration: 'Lamp',
      notes: 'Open vraag, drie minuten. Alleen voor wie bij de vorige vraag niet "nee" koos. Vraag om concreet gedrag, niet om een onderwerp als "AI". Eén of twee zinnen is genoeg.',
    },
    // 23 Afsluiting (1:52, 8 min)
    {
      type: 'closing',
      variant: 'roze',
      title: 'Afsluiting',
      question: 'Wat verloor en won je?',
      text: 'En wat doe je morgen anders?',
      points: [
        { tag: 'Meenemen', text: 'De skills staan in de repo, je kunt ze zelf aanpassen.' },
        { tag: 'Nog even', text: 'Een verschil is nog geen oorzaak.' },
      ],
      pointsTitle: 'Voor onderweg',
      notes: 'Rondje door de groep, één zin per persoon of op een kaartje. Sluit af met de contactslide. Verwijs voor echte data naar het CEDA-pakket eencijferho.',
    },
    { type: 'contact' },
  ],
};
