// Uitvoeringsdeck van de workshop "Agentic data science in het onderwijs" (120 min).
// Dit is wat op de dag op het scherm staat; het voorstel is 261005_workshop_rad_voorstel.deck.mjs.
// Draaiboek: workshop-rad/docs/programma-uitvoering.md. Casus: A (eerstejaarsuitval).
// Bouwen vanuit de projectroot:
//   node ~/.claude/skills/powerclaude/scripts/build.mjs workshop-rad/decks/261005_workshop_rad_uitvoering.deck.mjs
export default {
  title: 'Agentic data science in het onderwijs: jij stuurt, de agent bouwt',
  author: 'CEDA',
  slides: [
    // 1-4 Intro (0:00, 5 min)
    {
      type: 'title',
      kicker: 'CEDA · DAIR-bijeenkomst',
      title: 'Jij stuurt, de agent bouwt',
      lede: 'Agentic data science in het onderwijs',
      sub: '120 minuten · één casus · één dashboard',
      agenda: ['Data verkennen', 'Dashboard bouwen', 'Evaluatie en afsluiting'],
      tagline: 'Moving Education.',
      notes: 'Welkom. Zeg in een zin wat vandaag gebeurt: in tweetallen werken met een AI-agent aan één casus, en een dashboard opleveren dat de vraag beantwoordt. Schrijf de eindtijd op een bord: 15:00 bijvoorbeeld.',
    },
    { type: 'ceda' },
    {
      type: 'table',
      variant: 'licht-blauw',
      title: 'Zo loopt de middag',
      columns: ['Tijd', 'Blok', 'Duur'],
      widths: [0.15, 0.7, 0.15],
      rows: [
        ['0:00', 'Intro, synthetische data, casus', '17 min'],
        ['0:17', 'Skills, prompts en de devcontainer', '13 min'],
        ['0:30', 'Ronde 1: data verkennen', '22 min'],
        ['0:52', 'Spiegelmoment 1', '15 min'],
        ['1:07', 'Ronde 2: dashboard bouwen', '22 min'],
        ['1:29', 'Spiegelmoment 2', '15 min'],
        ['1:44', 'Evaluatie en afsluiting', '16 min'],
      ],
      notes: 'Loop het schema in dertig seconden door. Benadruk de spiegelmomenten: daar leer je het meest, omdat je ziet wat de groep naast je deed. Aan het eind één blok voor evaluatie en afsluiting: we vragen wat jullie ervan vonden en of er een vervolg moet komen. Bij elk spiegelmoment kijken we in de skill, niet in individuele dashboards.',
    },
    {
      type: 'section',
      variant: 'blauw',
      title: 'Jij stuurt, de agent programmeert',
      text: 'Er is geen goed of fout dashboard, alleen keuzes die je kunt uitleggen.',
      illustration: 'kunstmatigeintelligentie',
      notes: 'Spelregels: iedereen werkt via de agent, niemand hoeft te kunnen programmeren, wel kritisch kijken. Doel aan het eind: een kwalitatief antwoord op de casusvraag, onderbouwd met je dashboard.',
    },
    // 5 Synthetische data (0:05, 6 min)
    {
      type: 'split',
      variant: 'licht-roze',
      title: 'De data is synthetisch, het patroon is ingebouwd',
      bullets: [
        '**Fictief:** zelfde kolommen en codes als 1CHO, maar geen echte personen',
        '**Mag de agent in:** geen AVG-toets of verwerkersovereenkomst nodig',
        '**Bewust gemaakt:** er zit een echt verschil én een nep-verschil in',
        '**Alleen oefenen:** de kansen zijn onze keuze, geen werkelijkheid',
      ],
      illustration: 'Slot',
      notes: 'Wat is synthetisch: gegenereerd naar het patroon van een echt bestand. Zeg hardop: er zit één echt verschil in en één dat alleen toeval is, we vertellen niet welke. Dat is de oefening. Validatie tegen de werkelijkheid doen we niet; dat vraagt echte data buiten de devcontainer.',
    },
    // 6-7 Opdracht en casus (0:11, 6 min)
    {
      type: 'cards',
      variant: 'licht-geel',
      title: 'Onze casus: eerstejaarsuitval',
      items: [
        { badge: 'A', tag: 'De vraag', title: 'Wie stopt na jaar 1?', sections: [{ text: 'Welke eerstejaars stoppen binnen een jaar, en verschilt dat per sector en opleidingsvorm?' }] },
        { badge: '→', tag: 'Met de agent', title: 'Uitval laten uitrekenen', sections: [{ text: 'Jullie laten de agent per jaar uitrekenen hoeveel eerstejaars stoppen, en dat vergelijken per sector.' }] },
        { badge: '✓', tag: 'Wat je oplevert', title: 'Eén dashboard', sections: [{ text: 'Een dashboard dat de vraag beantwoordt, met de conclusie als titel.' }] },
      ],
      footer: 'Data: 3070 fictieve studenten, cohorten 2012-2023, één bestand: data/synthetisch_1cho.csv.',
      notes: 'Uitleg voor jezelf: een casus is het probleem waar alle tweetallen aan werken. Eerstejaarsuitval = eerstejaars die binnen een jaar stoppen. De vraag is wie dat zijn en of het per sector verschilt. De deelnemers laten de agent de cijfers uitrekenen; zij bepalen wat ze ermee doen. Casus A gekozen omdat de data daar het sterkst op aansluit. Let op: opleidingsvorm heeft maar één waarde (voltijd). Wie dat zelf ontdekt, ziet waarom verkennen loont. Noem het niet vooraf.',
    },
    {
      type: 'split',
      variant: 'licht-blauw',
      title: 'Werk in tweetallen, wissel per ronde',
      bullets: [
        '**Prompter:** typt de opdrachten aan de agent',
        '**Checker:** leest wat de agent teruggeeft en vraagt: klopt dit, en kunnen we dit zo laten zien?',
        '**Wissel** na ronde 1, zodat beiden beide rollen doen',
        '**Loop je vast?** Vraag de agent: leg uit wat je net deed',
      ],
      illustration: 'gesprek',
      notes: 'Verdeel de tweetallen nu. Niemand hoeft code te lezen: de prompter typt, de checker beoordeelt of het antwoord van de agent logisch is. Bij vragen van deelnemers: stel zelf een wedervraag (wat zou je de agent kunnen vragen?). Check dat per tweetal één laptop met de devcontainer werkt. Wat ze aan het eind in handen hebben: een eigen aanpak, gespiegeld aan de tweetallen om hen heen.',
    },
    // 8 Prompt, skill en agent (uitleg)
    {
      type: 'cards',
      variant: 'blauw',
      title: 'Agent, prompt en skill',
      items: [
        { tag: 'De uitvoerder', title: 'Agent', sections: [{ text: 'De AI die het werk doet. Hij leest je opdracht, schrijft en draait de code. Wij gebruiken Claude Code.' }, { label: 'Voorbeeld', text: 'Claude Code in de terminal', strong: true }] },
        { tag: 'Een losse opdracht', title: 'Prompt', sections: [{ text: 'Wat jij zelf typt. Elke keer anders, en het resultaat hangt af van hoe je het vraagt.' }, { label: 'Voorbeeld', text: '"Laat zien wie er uitvalt"', strong: true }] },
        { tag: 'Een vast stappenplan', title: 'Skill', sections: [{ text: 'Een tekstbestand met stappen en checks dat de agent volgt. Elke keer dezelfde werkwijze.' }, { label: 'Voorbeeld', text: 'Eerst profiel, dan definities, dan kleine groepen', strong: true }] },
      ],
      footer: 'In de rondes prompten jullie zelf. Bij de spiegelmomenten laten wij zien hoe een skill hetzelfde doet.',
      notes: 'Vergelijk met een collega. De agent is de collega die het werk doet. Een prompt is een mondelinge opdracht aan die collega: snel, maar elke keer anders. Een skill is een werkinstructie die je die collega geeft: dezelfde stappen en dezelfde controles, elke keer. Laat een echte SKILL.md zien, maximaal een minuut. Vuistregel: elke prompt die je drie keer typt, is een skill in wording. Zelf doen jullie de rondes met prompts; de skills laten wij zien bij de spiegelmomenten.',
    },
    {
      type: 'cards',
      variant: 'licht-groen',
      title: 'Drie skills die wij laten zien',
      items: [
        { badge: '1', tag: 'Spiegelmoment 1', title: '/workshop-verkennen', sections: [{ label: 'Doet', text: 'Data verkennen, kleine groepen signaleren, schetsen.' }, { label: 'Levert', text: 'data-profiel.md en schets.md', strong: true }] },
        { badge: '2', tag: 'Spiegelmoment 2', title: '/workshop-dashboard', sections: [{ label: 'Doet', text: 'Dashboard bouwen, met de checks erin verweven.' }, { label: 'Levert', text: 'app.py en berekeningen.py', strong: true }] },
        { badge: '3', tag: 'Evaluatie', title: '/workshop-reflectie', sections: [{ label: 'Doet', text: 'Terugblik en vervolgwensen in je eigen woorden.' }, { label: 'Levert', text: 'reflectie-naam.md', strong: true }] },
      ],
      footer: 'Jullie prompten zelf in de rondes. Wij laten de skills live draaien bij de spiegelmomenten.',
      notes: 'Noem de drie skills bij naam: /workshop-verkennen, /workshop-dashboard en /workshop-reflectie. De deelnemers gebruiken ze niet zelf in de rondes: de leider laat ze draaien bij de spiegelmomenten en legt dan uit wat erin staat en wat de skill afdwingt.',
    },
    // 9 Devcontainer en voorbeeldprompt (0:25, 5 min)
    {
      type: 'list',
      variant: 'licht-groen',
      title: 'Zo start je met de agent',
      items: [
        { title: 'Open de devcontainer', text: 'Alles staat klaar: Python, DuckDB, Streamlit, de data en de skills', status: 'Stap 1', color: 'groen' },
        { title: 'Start Claude Code', text: 'Typ claude in de terminal', status: 'Stap 2', color: 'groen' },
        { title: 'Probeer een eerste instructie', text: 'Lees data/synthetisch_1cho.csv en vertel in gewone taal wat erin zit', status: 'Stap 3', color: 'blauw' },
        { title: 'Stuur de agent aan', text: 'Jij prompt, de agent rekent en bouwt. De skills laten wij straks zien', status: 'Straks', color: 'oranje' },
      ],
      footnote: 'Duurt het starten langer dan een minuut? Roep iemand, dan zoeken we het samen uit.',
      notes: 'Doe de eerste instructie live voor, op het scherm. Laat zien dat de agent de code zichtbaar maakt. Lukt het starten van Claude Code niet binnen een paar minuten, dan is dat een signaal over de devcontainer en niet over de deelnemer. Houd hier genoeg tijd voor.',
    },
    // 10-11 Ronde 1 (0:30, 22 min)
    {
      type: 'section',
      variant: 'groen',
      number: 1,
      title: 'Ronde 1: ken je data',
      text: '22 minuten. Verken data en codebook voor je iets bouwt.',
      illustration: 'data',
      notes: 'Start de timer van 22 minuten. Loop rond; beantwoord vragen met een wedervraag. Let op: wie het laatste cohort meetelt (vertekend percentage), zit in de valkuil. Dat bespreken we bij het spiegelmoment.',
    },
    {
      type: 'cards',
      variant: 'licht-geel',
      title: 'Ronde 1: wat je doet en oplevert',
      numbered: true,
      items: [
        { tag: 'Verken', title: 'Wat zit erin?', sections: [{ text: 'Rijen, studenten, jaren, ontbrekende waarden, de definitie van uitval en instroom.' }] },
        { tag: 'Controleer', title: 'Wat mag je laten zien?', sections: [{ text: 'Kleine groepen en cohorten die nog niet afgelopen zijn. Wat telt wel en niet mee?' }] },
        { tag: 'Schets', title: 'Twee of drie views', sections: [{ text: 'Een schets op papier of in tekst van wat je gaat bouwen, met een conclusie als titel.' }] },
      ],
      footer: '**Oplevering:** begrip van de data, een schets en een eerste privacy-check.',
      notes: 'Dit is de bestuurder-navigator-ronde. Aan het eind van ronde 1 moeten ze kunnen zeggen hoeveel studenten en cohorten er zijn, welke cohorten niet waarneembaar zijn en waar kleine groepen zitten.',
    },
    // Spiegelmoment 1 (0:52, 15 min): de skill bespreken, geen individuele dashboards
    {
      type: 'section',
      variant: 'oranje',
      number: 2,
      title: 'Spiegelmoment 1: kijk in de skill',
      text: 'Wat zit er in /workshop-verkennen, en wat deed jij anders?',
      illustration: 'Boek puzzelstuk',
      notes: 'We kijken niet naar individuele schetsen, maar naar de skill. Vraag eerst twee tweetallen om één ding te noemen dat ze in ronde 1 tegenkwamen (één zin per tweetal). Loop daarna met de volgende twee dia\'s door de skill. Draai /workshop-verkennen live: dat duurt ongeveer 1 minuut (gemeten 58 tot 71 s, reken op een marge) en je legt uit terwijl hij loopt. Zet daarnaast desgewenst één gewone prompt op hetzelfde scherm.',
    },
    {
      type: 'cards',
      variant: 'licht-blauw',
      title: '/workshop-verkennen: vier stappen',
      numbered: true,
      arrows: true,
      items: [
        { tag: 'Stap 1', title: 'Profileren', sections: [{ text: 'Rijen, studenten, jaren, ontbrekende waarden en instroom per jaar.' }, { label: 'Levert', text: 'Overzicht in gewone taal', strong: true }] },
        { tag: 'Stap 2', title: 'Definities', sections: [{ text: 'Uitval, instroom en rendement volgens staat1cho, letterlijk vastgelegd.' }, { label: 'Levert', text: 'Afspraken', strong: true }] },
        { tag: 'Stap 3', title: 'Kleine groepen', sections: [{ text: 'Groepen onder 30 tellen en uitleggen waarom ze verborgen blijven.' }, { label: 'Levert', text: 'Privacy-check', strong: true }] },
        { tag: 'Stap 4', title: 'Schetsen', sections: [{ text: 'Twee of drie views met de conclusie als titel, plus wat het niet kan zeggen.' }, { label: 'Levert', text: 'schets.md', strong: true }] },
      ],
      footer: '**In:** data/synthetisch_1cho.csv en de casusvraag. **Uit:** data-profiel.md en schets.md.',
      notes: 'Dit is de opbouw van /workshop-verkennen/SKILL.md. Open het bestand even op het scherm: bovenaan staat wanneer de agent de skill pakt, daaronder de stappen. Vraag: welke van deze vier stappen heb jij in ronde 1 overgeslagen of anders gedaan?',
    },
    {
      type: 'cards',
      variant: 'licht-roze',
      title: 'Wat skill 1 voor je afvangt',
      items: [
        { tag: 'Valkuil', title: 'Laatste cohort', sections: [{ text: 'Cohort 2023 is nog niet afgelopen en geeft 100% uitval. De skill sluit het uit en meldt dat.' }] },
        { tag: 'Valkuil', title: 'Eén waarde', sections: [{ text: 'Opleidingsvorm is overal voltijd. De skill meldt dat en laat die uitsplitsing weg.' }] },
        { tag: 'Privacy', title: 'Kleine groepen', sections: [{ text: '28 van de 96 groepen hebben minder dan 30 studenten en worden niet getoond.' }] },
        { tag: 'Framing', title: 'Geen oorzaak', sections: [{ text: 'Een verschil heet nooit effect. De skill schrijft op wat het dashboard niet kan zeggen.' }] },
      ],
      footer: 'Wat misten jullie zelf, en wat zagen jullie juist wel? Dat is de vraag voor dit moment.',
      notes: 'Dit zijn de checks die in de skill zijn verweven. Laat de deelnemers zelf aanwijzen welke ze in ronde 1 zelf hebben gedaan. De cijfers komen uit de antwoordsleutel (workshop-rad/data/verwachte_uitkomsten.txt). De drempel 30 en 5 is een keuze van staat1cho en niet getoetst door een privacy officer.',
    },
    // 14-16 Ronde 2 (1:07, 22 min)
    {
      type: 'section',
      variant: 'blauw',
      number: 3,
      title: 'Ronde 2: bouw het dashboard',
      text: '22 minuten. Wissel van rol en maak de conclusie zichtbaar.',
      illustration: 'Laptopman',
      notes: 'Wissel nu van rol. Timer 22 minuten. Loop rond met de responsible-checks in je hoofd: drempel, waarneembaarheid, framing, toegankelijkheid.',
    },
    {
      type: 'cards',
      variant: 'licht-groen',
      title: 'Wat je dashboard minimaal heeft',
      numbered: true,
      items: [
        { tag: 'Grafiek', title: 'Conclusie als titel', sections: [{ text: '"Uitval is het hoogst in techniek" in plaats van "Uitval per sector".' }] },
        { tag: 'Vergelijking', title: 'Eén nul-as', sections: [{ text: 'Groepen of cohorten naast elkaar, vergelijkbaar en eerlijk.' }] },
        { tag: 'Filter', title: 'Sector of cohort', sections: [{ text: 'Ook na het filteren worden kleine groepen niet getoond.' }] },
        { tag: 'Uitleg', title: 'Zo lees je dit', sections: [{ text: 'Definities, bron en wat het dashboard niet kan zeggen.' }] },
      ],
      footer: 'Het dashboard is het middel, de casusvraag het doel.',
      notes: 'Dit zijn de vier minimumeisen. Meer hoeft niet; liever een werkend en uitlegbaar dashboard dan een volle tabbladenwand.',
    },
    {
      type: 'cards',
      variant: 'licht-roze',
      title: 'Responsible zit in het bouwen',
      items: [
        { tag: 'Privacy', title: 'Drempel', sections: [{ text: 'Geen groepen onder de 30 studenten, geen percentages onder 5.' }] },
        { tag: 'Eerlijk', title: 'Geen oorzaak', sections: [{ text: 'Een verschil is nog geen oorzaak, en groepen worden niet gestigmatiseerd.' }] },
        { tag: 'Toegankelijk', title: 'Leesbaar', sections: [{ text: 'Kleurcontrast, alt-tekst en kleuren die ook zonder rood-groen werken.' }] },
        { tag: 'Bron', title: 'Uitleg', sections: [{ text: 'Bron, definities en peildatum bij elke grafiek.' }] },
      ],
      footer: 'Geen aparte stap achteraf: de skill past deze checks toe tijdens het bouwen.',
      notes: 'De agent bouwt snel. Jij bepaalt wat je mag concluderen. Na ronde 2 zie je wat jullie zelf misten.',
    },
    // Spiegelmoment 2 (1:29, 15 min): de skill bespreken, daarna de onthulling
    {
      type: 'section',
      variant: 'oranje',
      number: 4,
      title: 'Spiegelmoment 2: kijk in de skill',
      text: 'Wat zit er in /workshop-dashboard, en wat miste je dashboard?',
      illustration: 'Puzzelstuk 3D',
      notes: 'Ook nu geen individuele dashboards bekijken. Vraag twee tweetallen om één keuze te noemen die ze maakten (bijvoorbeeld de titel of de drempel). Draai /workshop-dashboard live: dat duurt ongeveer 2 tot 2,5 minuut (gemeten 124 tot 136 s). Loop daarna door de skill met de volgende dia\'s en sluit af met de onthulling van de uitkomst. Contrast: een gewone prompt telt de eerstejaars anders (2.449 in plaats van 2.809) en verbergt kleine groepen niet; zie docs/tijdmeting.md.',
    },
    {
      type: 'cards',
      variant: 'licht-blauw',
      title: '/workshop-dashboard: wat de skill doet',
      numbered: true,
      arrows: true,
      items: [
        { tag: 'Leest in', title: 'Profiel en schets', sections: [{ text: 'data-profiel.md, schets.md en de data zelf.' }, { label: 'Levert', text: 'Vaste invoer', strong: true }] },
        { tag: 'Bouwt', title: 'Het dashboard', sections: [{ text: 'app.py voor de weergave, berekeningen.py voor de rekenregels.' }, { label: 'Levert', text: 'Werkend dashboard', strong: true }] },
        { tag: 'Verweeft', title: 'De checks', sections: [{ text: 'Drempel, framing, toegankelijkheid en bron.' }, { label: 'Levert', text: 'Verantwoord', strong: true }] },
        { tag: 'Test', title: 'Headless', sections: [{ text: 'AppTest: geen fouten en een kleine groep geeft "te weinig studenten".' }, { label: 'Levert', text: 'Aantoonbaar', strong: true }] },
      ],
      footer: '**In:** de twee bestanden uit ronde 1. **Uit:** een werkend, verantwoord dashboard.',
      notes: 'Dit is de opbouw van /workshop-dashboard/SKILL.md. Let op het verschil met ronde 1: hier staan de responsible-checks niet in een aparte stap maar in de bouwinstructie zelf.',
    },
    {
      type: 'table',
      variant: 'licht-geel',
      title: 'Zo verweeft de skill de checks',
      columns: ['Check', 'Wat de skill in het dashboard doet'],
      widths: [0.25, 0.75],
      rows: [
        ['Privacy', 'Groepen onder 30 en percentages onder 5 niet tonen; de drempel is een parameter'],
        ['Waarneembaarheid', 'Cohorten waarvan de termijn nog niet af is uitsluiten en dat melden'],
        ['Eerlijke framing', 'Conclusie als titel, geen oorzaak, geen stigmatiserende woorden'],
        ['Toegankelijkheid', 'Kleurenblind-veilig palet, contrast 4,5:1, tekstuele samenvatting per grafiek'],
        ['Bron en uitleg', 'Bron, definities, peildatum, n per groep en wat het niet kan zeggen'],
      ],
      notes: 'Vraag per rij: heb jij dit in je dashboard zelf gedaan? De skill doet het elke keer zonder dat je eraan hoeft te denken. Dat is het verschil tussen een prompt en een skill.',
    },
    {
      type: 'chart',
      variant: 'licht-geel',
      title: 'Techniek valt het vaakst uit, geslacht laat geen verschil zien',
      chart: 'bar',
      labels: ['Techniek', 'Economie', 'Gezondheidszorg', 'Totaal'],
      series: [{ name: 'Uitval binnen 1 jaar', values: [21.9, 13.1, 10.2, 16.7] }],
      format: '0.0"%"',
      takeaway: 'Het verschil tussen sectoren hebben wij ingebouwd. Man (16,1%) en vrouw (17,3%) verschillen niet echt: dat is toeval.',
      source: 'synthetische data, cohorten 2012-2022 (2023 is nog niet waarneembaar)',
      notes: 'De onthulling: dit is wat een correcte analyse oplevert. Vraag of de skill dit ook vond. Wie in ronde 2 "vrouwen vallen vaker uit" had, ziet hier ruis. Gebruik dit als leermoment zonder beschuldiging. Antwoordsleutel: workshop-rad/data/verwachte_uitkomsten.txt.',
    },
    // Evaluatie en afsluiting in één blok (1:44, 16 min)
    {
      type: 'cards',
      variant: 'groen',
      title: 'Evaluatie en afsluiting: 16 minuten',
      items: [
        { badge: '1', tag: '4 min', title: 'Terugblik', sections: [{ text: 'Wat vond je ervan? Wat ging goed, wat zag je nu pas?' }] },
        { badge: '2', tag: '2 min', title: 'Meerkeuze', sections: [{ text: 'Zou je een vervolg willen, en hoe groot?' }] },
        { badge: '3', tag: '4 min', title: 'Open vraag', sections: [{ text: 'Wat wil je precies leren in zo\u2019n training?' }] },
        { badge: '4', tag: '6 min', title: 'Afsluiting', sections: [{ text: 'Wat verloor en won je, en wat doe je morgen anders?' }] },
      ],
      footer: 'Anoniem en vrijwillig. De antwoorden bepalen of en hoe CEDA een vervolg inricht.',
      notes: 'Evaluatie en afsluiting zijn één blok van 16 minuten. Vraag eerst toestemming: de antwoorden zijn anoniem en gebruiken we om te bepalen of er een vervolg komt. Terugblik via /workshop-reflectie of de peiling (QR-code). Houd de tijd: loopt het uit, kort dan de afsluiting in, niet de peiling.',
    },
    {
      type: 'cards',
      variant: 'licht-groen',
      title: '/workshop-reflectie: wat de skill doet',
      numbered: true,
      arrows: true,
      items: [
        { tag: 'Toestemming', title: 'Eén zin', sections: [{ text: 'Anoniem, om te bepalen of er een vervolg komt. Zonder ja wordt niets bewaard.' }] },
        { tag: 'Terugblik', title: 'Drie vragen', sections: [{ text: 'Werkwijze, wat ging goed en wat zie je nu pas. Eén vraag per keer.' }] },
        { tag: 'Peiling', title: 'Meerkeuze', sections: [{ text: 'Interesse in een training, van nee tot 4 uur per week voor een semester.' }] },
        { tag: 'Open vraag', title: 'Wat leren?', sections: [{ text: 'Alleen als het antwoord niet nee was. Kort en concreet.' }] },
      ],
      footer: '**Uit:** reflectie-naam.md, in jouw eigen woorden. De skill vult niets voor je in.',
      notes: 'Dit is de opbouw van /workshop-reflectie/SKILL.md: afgeleid van de teamskill sessie-terugblik, zonder GitHub-koppeling. Principes: één vraag per keer, een dun antwoord is een antwoord, niet doorvragen. Deelnemers mogen kiezen: via de skill of via de peiling.',
    },
    {
      type: 'list',
      variant: 'licht-blauw',
      title: 'Zou je een vervolg op deze workshop willen?',
      items: [
        { title: 'Nee, niet nodig', text: 'Deze workshop was genoeg', status: 'A', color: 'blauw' },
        { title: 'Een losse sessie van een paar uur', text: 'Een vervolgworkshop, bijvoorbeeld met eigen data', status: 'B', color: 'blauw' },
        { title: 'Een paar dagdelen over enkele weken', text: 'Verdieping verspreid over meerdere dagen', status: 'C', color: 'blauw' },
        { title: '4 uur per week, één semester', text: 'Een volledig trainingsprogramma', status: 'D', color: 'blauw' },
      ],
      footnote: 'Kies wat het best past. Scan de QR-code of steek je hand op.',
      notes: 'Laat de peiling lopen, twee minuten. Als de peiling-tool nog niet gekozen is, tel handopsteking en noteer de aantallen. Voeg de QR-code hier toe zodra de tool bekend is.',
    },
    {
      type: 'section',
      variant: 'geel',
      title: 'Wat wil je precies leren?',
      text: 'Kort en concreet. Bijvoorbeeld: een eigen skill schrijven voor onze data.',
      illustration: 'Lamp',
      notes: 'Open vraag, vier minuten. Alleen voor wie bij de vorige vraag niet "nee" koos. Vraag om concreet gedrag, niet om een onderwerp als "AI". Eén of twee zinnen is genoeg.',
    },
    {
      type: 'closing',
      variant: 'roze',
      title: 'Afsluiting',
      question: 'Wat verloor en won je?',
      text: 'En wat doe je morgen anders?',
      points: [
        { tag: 'Meenemen', text: 'De drie skills staan in de repo, je kunt ze zelf aanpassen.' },
        { tag: 'Nog even', text: 'Een verschil is nog geen oorzaak.' },
      ],
      pointsTitle: 'Voor onderweg',
      notes: 'Rondje door de groep, één zin per persoon of op een kaartje (circa 6 minuten). Sluit af met de contactslide. Verwijs voor echte data naar het CEDA-pakket eencijferho.',
    },
    { type: 'contact' },
  ],
};
