// Workshop-voorstel RAD / DAIR (120 min), herbouwd met powerclaude zodat logo, illustraties en
// vormtaal de echte Npuls-huisstijl volgen. Inhoud komt uit workshop-voorstel-RAD_120min.pptx (v1),
// aangevuld met het evaluatieblok (reflectie, interesse in een training, vervolg).
// Bouwen vanuit de projectroot: node ~/.claude/skills/powerclaude/scripts/build.mjs workshop-rad/decks/261005_workshop_rad_voorstel.deck.mjs
export default {
  title: 'Agentic data science in het onderwijs: workshop-voorstel',
  author: 'CEDA',
  slides: [
    {
      type: 'title',
      kicker: 'CEDA · DAIR-bijeenkomst',
      title: 'Agentic data science in het onderwijs',
      lede: 'Workshop-voorstel: korte rondes met spiegelen',
      sub: '120 minuten · één casus · één dashboard',
      agenda: ['Data exploratie', 'Dashboard bouwen', 'Evaluatie en vervolg'],
      tagline: 'Moving Education.',
      notes: 'Dit is het voorstel, niet de uitvoering. We leggen het format voor en vragen om akkoord op de keuzes en de open punten achterin.',
    },
    { type: 'ceda' },
    {
      type: 'stats',
      variant: 'roze',
      title: 'Eén casus, één dashboard, twee rondes',
      lede: 'AI is geen black box maar een transparante junior-analist. De agent versnelt het handwerk, de deelnemers houden de regie.',
      items: [
        { value: '120', label: 'minuten', text: 'één workshop, elf blokken' },
        { value: '2', label: 'rondes', text: 'exploreren en bouwen, allebei verantwoord' },
        { value: '2', label: 'spiegelmomenten', text: 'elk met een skill die de stap ervoor doet' },
        { value: '1', label: 'casus', text: 'beantwoord met één dashboard' },
      ],
      callout: '**Wow-moment:** elke ronde een zichtbare sprong. De skill doet de vorige stap in één instructie, gespiegeld aan de groep ernaast.',
      footnote: 'Data is synthetisch: validatie tegen de werkelijkheid hoort niet bij de workshop en vraagt echte data, buiten de devcontainer.',
      notes: 'De vier getallen vatten het format samen. Nieuw ten opzichte van v1: aan het eind een evaluatieblok met reflectie en een peiling naar interesse in een training.',
    },
    {
      type: 'table',
      variant: 'licht-blauw',
      title: 'Programma: 120 minuten in acht stappen',
      columns: ['Tijd', 'Blok', 'Duur', 'Wat gebeurt er'],
      widths: [0.1, 0.3, 0.1, 0.5],
      rows: [
        ['0:00', 'Intro, synthetische data, casus', '17 min', 'Waarom agentic data science, wat is synthetisch, welke vraag beantwoorden we'],
        ['0:17', 'Skills, prompts, devcontainer', '13 min', 'Wat is een skill, hoe spreek je de agent aan, voorbeeldprompt'],
        ['0:30', 'Ronde 1: data exploratie', '22 min', 'Data en codebook verkennen, kleine groepen en definities checken'],
        ['0:52', 'Spiegelmoment 1', '15 min', '2-3 tweetallen delen hun aanpak, daarna doet skill 1 de ronde'],
        ['1:07', 'Ronde 2: dashboard bouwen', '22 min', 'Eerlijke framing en toegankelijke grafieken in één dashboard'],
        ['1:29', 'Spiegelmoment 2', '15 min', 'Toon 2-3 dashboards, daarna doet skill 2 de ronde'],
        ['1:44', 'Evaluatie en vervolg', '8 min', 'Reflectie, peiling naar een training, wat wil je leren'],
        ['1:52', 'Interactieve afsluiting', '8 min', 'Wat verloor en won je, wat neem je mee'],
      ],
      notes: 'Het evaluatieblok staat na de laatste uitleg (spiegelmoment 2) en vóór de interactieve afsluiting. De uitleg-blokken aan het begin zijn ten opzichte van v1 iets ingekort om die 8 minuten vrij te maken.',
    },
    {
      type: 'cards',
      variant: 'roze',
      title: 'Wat is synthetische data?',
      items: [
        { title: 'Veilig', illustration: 'Slot', sections: [{ label: 'Fictieve rijen', text: 'Zelfde kolommen en codes als 1CHO, maar geen enkele rij is een bestaand persoon.' }] },
        { title: 'Open', illustration: 'kunstmatigeintelligentie', sections: [{ label: 'Mag de agent in', text: 'Geen AVG-toets of verwerkersovereenkomst nodig: de data mag de devcontainer en de agent in.' }] },
        { title: 'Let op', illustration: 'Lamp', sections: [{ label: 'Bewust gemaakt', text: 'Een patroon en enkele kleine groepen zijn ingebakken, zodat er iets te vinden én te blokkeren is.' }] },
      ],
      footer: '**Je oefent de werkwijze, niet de uitkomst.** Validatie vraagt echte data, buiten de devcontainer.',
      notes: 'Synthetisch is niet willekeurig: de verdelingen lijken op de werkelijkheid, de personen bestaan niet. Zelfde codebook, zelfde definities, dus wat je bouwt werkt straks ook op echte data.',
    },
    {
      type: 'cards',
      variant: 'licht-geel',
      title: 'De opdracht in drie stappen',
      numbered: true,
      arrows: true,
      items: [
        { tag: 'Vraag', title: 'Kies de casus', sections: [{ label: 'Hoe', text: 'Eén casusvraag over het 1CHO-bestand staat de hele sessie centraal.' }, { label: 'Resultaat', text: 'Een scherpe vraag die je aan het eind kunt beantwoorden.', strong: true }] },
        { tag: 'Samen', title: 'Werk in tweetallen', sections: [{ label: 'Hoe', text: 'Eén stuurt de agent aan, de ander controleert code en uitkomst. Wissel per ronde.' }, { label: 'Resultaat', text: 'Een eigen aanpak, gespiegeld aan de tweetallen om je heen.', strong: true }] },
        { tag: 'Product', title: 'Lever één dashboard', sections: [{ label: 'Hoe', text: 'Bouw in twee rondes een dashboard dat de vraag beantwoordt.' }, { label: 'Resultaat', text: 'Een kwalitatief antwoord, onderbouwd met het dashboard.', strong: true }] },
      ],
      footer: 'Er is geen goed of fout dashboard. Het gaat om de keuzes die je maakt, en of je ze kunt uitleggen.',
      notes: 'De bestuurder prompt, de navigator controleert wat de agent doet. Na elke ronde een spiegelmoment: 2-3 tweetallen laten zien wat ze deden, daarna laten we zien wat de skill in één instructie doet.',
    },
    {
      type: 'cards',
      variant: 'licht-blauw',
      title: 'Drie casussen, wij kiezen er één',
      items: [
        { badge: 'A', tag: '1CHO', title: 'Eerstejaarsuitval', sections: [{ label: 'Vraag', text: 'Welke eerstejaars stoppen binnen een jaar, en verschilt dat per sector en opleidingsvorm?' }, { label: 'AI-taak', text: 'Uitval binnen 1 jaar per cohort berekenen en vergelijken.' }] },
        { badge: 'B', tag: '1CHO', title: 'Wisselen of stoppen?', sections: [{ label: 'Vraag', text: 'Stoppen studenten of wisselen ze van opleiding, en waar gaan de wisselaars heen?' }, { label: 'AI-taak', text: 'Uitval en wissel onderscheiden, stromen tonen.' }] },
        { badge: 'C', tag: '1CHO', title: 'VO-cijfers en studiesucces', sections: [{ label: 'Vraag', text: 'Halen studenten met hoge VO-cijfers vaker binnen vijf jaar hun diploma?' }, { label: 'AI-taak', text: 'Rendement koppelen aan het VO-eindcijfer en de vooropleiding.' }] },
      ],
      footer: '**Doel:** aan het eind een kwalitatief antwoord op de casusvraag, onderbouwd met het dashboard.',
      footnote: 'Definities van uitval, rendement en studiewissel volgen het package staat1cho.',
      notes: 'Alle drie draaien op het 1CHO-bestand. Let op: casus C vraagt een VO-eindcijfer, dat zit niet in het synthetische inschrijvingenbestand maar in VAKHAVW. Zie de bevindingen uit staat1cho in de uitvoeringsdocumentatie.',
    },
    {
      type: 'cards',
      variant: 'blauw',
      title: 'Wat is een skill?',
      arrows: true,
      items: [
        { tag: 'Losse vraag', title: 'Prompt', sections: [{ text: 'Je typt wat je wilt. Het resultaat is elke keer anders en de kennis zit alleen in jouw hoofd.' }, { label: 'Levert', text: 'Eén antwoord', strong: true }] },
        { tag: 'Vastgelegd recept', title: 'Skill', sections: [{ text: 'Een map met een SKILL.md: instructies, voorbeelden, scripts en checks. De agent pakt hem erbij.' }, { label: 'Levert', text: 'Herhaalbare werkwijze', strong: true }] },
        { tag: 'Voert uit', title: 'Agent', sections: [{ text: 'Claude Code leest de skill, draait de code en toetst het resultaat aan de checks.' }, { label: 'Levert', text: 'Resultaat dat je kunt nalopen', strong: true }] },
      ],
      footer: 'Een skill is gewoon tekst in de repo: leesbaar, aanpasbaar en deelbaar. Programmeren hoeft niet.',
      notes: 'Prompt: wat je nu al doet. Skill: een map met een SKILL.md, bovenaan staat wanneer hij van toepassing is. De agent leest alleen de korte beschrijving en laadt de rest pas als de taak erom vraagt.',
    },
    {
      type: 'stats',
      variant: 'roze',
      title: 'Van prompt naar teamkennis',
      lede: 'Een goede prompt helpt jou vandaag. Een goede skill helpt je hele team, elke keer weer.',
      items: [
        { value: '1×', label: 'uitschrijven', text: 'daarna eindeloos hergebruiken, door iedereen' },
        { value: '0', label: 'black boxes', text: 'je leest precies wat de agent gaat doen' },
        { value: 'n<30', label: 'ingebouwd', text: 'privacy-drempel en checks vergeet je nooit meer' },
        { value: '€0', label: 'kosten', text: 'tekstbestanden in de repo, deelbaar via Git' },
      ],
      callout: '**Vuistregel:** elke prompt die je drie keer typt, is een skill in wording.',
      notes: 'Herkenbaar: je schrijft een goede prompt, het werkt, en een week later typ je hem opnieuw (en net iets anders). De drempel is een keuze van het project (staat1cho: minder dan 30 studenten per groep, minder dan 5 per percentage-cel), nog niet getoetst door een privacy officer.',
    },
    {
      type: 'list',
      variant: 'licht-groen',
      title: 'Wat komt er in de devcontainer?',
      items: [
        { title: 'AI-agent: Claude Code', text: 'de agent waarmee iedereen werkt; jij stuurt, de agent programmeert', status: 'Vast', color: 'groen' },
        { title: 'Python', text: 'de agent schrijft de analyse, bijvoorbeeld met DuckDB', status: 'Vast', color: 'groen' },
        { title: 'Data en codebook', text: 'synthetisch 1CHO-CSV, gelabelde waarden', status: 'Vast', color: 'groen' },
        { title: 'Skills en checkpoints', text: 'staan klaar, activeren met één commando', status: 'Vast', color: 'groen' },
        { title: 'Dashboard: Streamlit', text: 'nog niet zeker, de tool kan nog wijzigen', status: 'Open', color: 'oranje' },
      ],
      footnote: 'Het concept staat, de invulling is deels open. Geen programmeerervaring nodig, wel kritisch kijken: klopt wat de agent doet?',
      notes: 'Iedereen werkt via de agent. Streamlit is een voorlopige keuze: het staat1cho-dashboard zelf is in R Shiny gebouwd, maar voor de workshop is Python met de agent het meest haalbaar.',
    },
    {
      type: 'cards',
      variant: 'licht-geel',
      title: 'Eén dashboard, twee stappen',
      numbered: true,
      arrows: true,
      items: [
        { tag: 'Data → Informatie', title: 'Ronde 1: data exploratie', sections: [{ label: 'Wat je doet', text: 'Data en codebook verkennen met de agent, de code controleren en kleine groepen en definities vastleggen.' }, { label: 'Wat ontstaat', text: 'Begrip van de data, een schets van twee of drie views en een eerste privacy-check.', strong: true }] },
        { tag: 'Informatie → Wijsheid', title: 'Ronde 2: dashboard bouwen', sections: [{ label: 'Wat je doet', text: 'Grafiek, vergelijking en filter bouwen, met eerlijke framing, bron en toegankelijke grafieken.' }, { label: 'Wat ontstaat', text: 'Een werkend én verantwoord dashboard, bij voorkeur met de conclusie als titel.', strong: true }] },
      ],
      footer: 'Het dashboard is het middel, de casusvraag het doel. De analist voegt de wijsheid toe.',
      notes: 'Wat mag je concluderen en hoe presenteer je het? Dat is het werk dat de agent niet voor je doet.',
    },
    {
      type: 'cards',
      variant: 'licht-blauw',
      title: 'Een skill bij elk moment',
      items: [
        { badge: '1', tag: 'Doet ronde 1', title: 'Verkennen', sections: [{ text: 'Profileert CSV en codebook, signaleert kleine groepen, legt definities vast en schetst twee of drie views.' }, { label: 'Levert', text: 'Data-profiel, privacy-check en schets', strong: true }] },
        { badge: '2', tag: 'Doet ronde 2', title: 'Dashboard', sections: [{ text: 'Bouwt uit de schets een dashboard met grafiek, vergelijking en filter, met drempel, framing, bron en toegankelijkheid erin verweven.' }, { label: 'Levert', text: 'Werkend én verantwoord dashboard', strong: true }] },
        { badge: '3', tag: 'Bij de evaluatie', title: 'Reflectie', sections: [{ text: 'Stelt dezelfde vaste vragen aan elke deelnemer en legt de antwoorden vast in hun eigen woorden.' }, { label: 'Levert', text: 'Reflectie en vervolgwensen', strong: true }] },
      ],
      footer: 'Skills werken via vaste tussenproducten (data.csv, schets.md), zodat elke stap na te lopen is.',
      notes: 'Nieuw: een derde skill voor de reflectie. Die is afgeleid van de bestaande sessie-terugblik van het team, maar zonder GitHub-koppeling: de antwoorden komen in een lokaal bestand en in de peiling.',
    },
    {
      type: 'cards',
      variant: 'licht-roze',
      title: 'Responsible zit in beide rondes',
      items: [
        { tag: 'Ronde 1 + 2', title: 'Privacy-check', sections: [{ text: 'Drempel voor kleine aantallen en herleidbare combinaties van uitsplitsingen.' }] },
        { tag: 'Ronde 2', title: 'Toegankelijkheid', sections: [{ text: 'Kleurcontrast, alt-tekst en een dashboard dat een bestuurder echt kan lezen.' }] },
        { tag: 'Ronde 2', title: 'Eerlijke framing', sections: [{ text: 'Cijfers per groep mogen niet stigmatiseren, en een verband is nog geen oorzaak.' }] },
        { tag: 'Ronde 1 + 2', title: 'Bron en uitleg', sections: [{ text: 'Definities uit het codebook, bronvermelding en uitleg bij elke grafiek.' }] },
      ],
      footer: 'Geen aparte stap: elke skill past de checks toe die bij zijn ronde horen.',
      notes: 'De agent bouwt snel. Jij bepaalt wat je mag concluderen. Na elke ronde zie je wat de tweetallen zelf misten.',
    },
    {
      type: 'cards',
      variant: 'groen',
      title: 'Evaluatie en vervolg: 8 minuten',
      items: [
        { badge: '1', tag: '3 min', title: 'Reflectie', sections: [{ text: 'Wat vond je ervan? Wat ging goed, wat zag je nu pas, wat neem je mee? Via de reflectie-skill of de peiling.' }] },
        { badge: '2', tag: '2 min', title: 'Meerkeuzevraag', sections: [{ text: 'Interesse in een training? Van nee tot een programma van 4 uur per week voor één semester.' }] },
        { badge: '3', tag: '3 min', title: 'Open vraag', sections: [{ text: 'Wat wil je precies leren in zo’n training? Kort en concreet, in je eigen woorden.' }] },
      ],
      footer: 'De antwoorden bepalen of en hoe CEDA een vervolg inricht.',
      notes: 'Plek in het programma: na de laatste uitleg (spiegelmoment 2) en vóór de interactieve afsluiting. Antwoordopties MC: nee / losse sessie / paar dagdelen / programma van 4 uur per week voor één semester. Tool voor de peiling is nog open.',
    },
    {
      type: 'table',
      variant: 'licht-geel',
      title: 'Randvoorwaarden en risico’s',
      columns: ['Risico', 'Maatregel'],
      widths: [0.4, 0.6],
      rows: [
        ['Deelnemers zonder codeerervaring haken af', 'Iedereen werkt alleen via prompten; de voorbeeldprompt en de skills geven houvast.'],
        ['De agent is niet deterministisch', 'Per ronde een checkpoint met het verwachte resultaat en minstens twee droge runs vooraf.'],
        ['Skills uitdelen kost tijd', 'Skills staan klaar in de devcontainer en activeren met één commando (maximaal 1 minuut).'],
        ['Responsible raakt ondergesneeuwd', 'De checks zitten verweven in beide skills, plus een korte checklist per ronde.'],
        ['Data zonder patroon of kleine groepen', 'Vooraf controleren en zo nodig een patroon en enkele kleine groepen inbouwen.'],
        ['Evaluatie loopt uit of krijgt weinig respons', 'Vaste 8 minuten, peiling via QR-code, reflectie-skill als optie voor wie meer wil kwijt.'],
      ],
      notes: 'Het laatste risico is nieuw. Als de rondes uitlopen, schrappen we eerst de interactieve afsluiting, niet de evaluatie: die levert de input voor een vervolg.',
    },
    {
      type: 'closing',
      variant: 'roze',
      title: 'Open punten',
      question: 'Welke casus kiezen we?',
      points: [
        { tag: 'Casus', text: 'Kies A, B of C: alle drie op het 1CHO-bestand.' },
        { tag: 'Tools', text: 'Dashboard-tool en peiling-tool nog kiezen.' },
      ],
      pointsTitle: 'Nog te beslissen',
      notes: 'Vraag om akkoord op de casus en de peiling-tool. Daarna werken we de uitvoering uit.',
    },
    { type: 'contact' },
  ],
};
